In [2]:
import numpy as np

### np.zeros :
* np.zeros is a function that creates an array filled with zeros. You specify the shape of the array (the number of rows and columns) as an argument, and the function returns an array of that shape, where all the elements are set to zero.
* This function is useful when you need to initialize an array with zeros 

### 1. Write a program to create a 5 dimensional array with all zeros and ones

In [239]:
x= np.zeros((5,3,3)) 
print(x)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### np.ones ( )
* np.ones, which creates an array filled with ones.

In [240]:
x = np.ones((5,2,5)) 
print(x)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 2. Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

### np.full ( ):
*  The np.full() function is used to create an array of a specified shape and fill it with a constant value. It takes the shape of the array and the constant value as its primary arguments.
* This function is useful when you want to create an array with a constant value across all its elements.

In [190]:
x=np.array([np.zeros(10),np.ones(10),np.full(10,5)]) ## here we passing elements in a list
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


### 3. Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [84]:
zz=np.arange(10,22).reshape(3,4) ## arange is nothing but a range function ,arange(start,end,step)-->we have to pass the arguments like that
zz

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 4. Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

### Identity matrix
* An identity matrix is a special type of square matrix where all the elements in the main diagonal (from the top-left to the bottom-right) are equal to 1, and all other elements are equal to 0.
* we have functions that is used to create an identity matrix.

### np.eye
* np.eye() function takes the number of rows (and optionally, the number of columns) as its argument 

In [101]:
xx=np.eye(10)
print(xx,sep='\n')


for i in range(10):
    xx[i,i]=i  ## eache diagonal element is replaces with 0 to 9 
print('\n',xx) 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


#### Another way, by using default attribute diag(diagnol)

In [102]:
replace_diagnols = np.diag(np.arange(10))
print(replace_diagnols)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


### 5. Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [107]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
c[::-1]  ## rows swapping

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [110]:
c[::-1,::-1] ## swapping of elements in a row 

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### 6.Write a program to reverse an array (the first element becomes the last).

In [115]:
array=np.arange(11)
print(array,array[::-1],sep='\n')

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


### 7. Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [155]:
numbers=np.arange(1,101).reshape(10,10)
print(numbers)
#y=[]
#if (numbers>30) & (numbers<80) & (numbers%5==0):
    #y.append(numbers)
#print(y)
y = numbers[np.where((numbers > 30) & (numbers < 80) & (numbers % 5 == 0))]
print('\n', y)
#z=[numbers if (numbers > 30) & (numbers < 80) & (numbers % 5 == 0) else '']

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

 [35 40 45 50 55 60 65 70 75]


### 8. Write a program to create a 2D array with 1 on the border and 0 inside.


In [259]:
a=np.ones((2,5,5))
a[0][1:4,1:4]=0  ## here im using slicing for filling zeros inside
a[1][1:4,1:4]=0
print(a)





[[[1. 1. 1. 1. 1.]
  [1. 0. 0. 0. 1.]
  [1. 0. 0. 0. 1.]
  [1. 0. 0. 0. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 0. 0. 0. 1.]
  [1. 0. 0. 0. 1.]
  [1. 0. 0. 0. 1.]
  [1. 1. 1. 1. 1.]]]


In [264]:
b=np.zeros((5,5))
b[1:4,1:4]=1  ## here im using slicing for filling ones inside
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 9.Write a program to create a checkerboard pattern .Don't use default array function
Checkerboard pattern:                                                   
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]


In [86]:
zero=np.zeros((10,10))
print(zero)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [89]:
zero[::2, 1::2] = 1  
zero[1::2,::2]=1


In [90]:
print(zero)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


### 10.Write a program to find common values between two arrays.
Expected Output:
array1: [10 20 40 60]
array2: [10, 30, 40,50]


In [10]:
array1 = np.array([10, 20, 40, 60])
array2 = np.array([10, 30, 40, 50])

common_values = np.intersect1d(array1, array2)
print(common_values)


[10 40]


### 11 Write a program to create an array 2d array and then reshape into 1d array

### ravel ( ):
* we can use ravel method to convert 2D array into 1D array

In [198]:
array=np.arange(1,21).reshape(2,10)
one_dim=array.ravel()
print(array,one_dim,sep='\n') 

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
