###  1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [3]:
import numpy as np 

In [4]:
array=np.random.randint(1,100,10) ## printing numbers randomly 

In [5]:
print(f' array is {array}') 

 array is [ 3 94 70  4 55 81 31 41  9 98]


In [64]:
def foo_1(arr, target):
    if target not in arr:
        return 'No Item Found'
    differences = np.absolute(arr - target)  
    indices = np.argsort(differences)
    return indices

In [65]:
array=np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])

In [66]:
foo_1(array,7)

array([2, 3, 4, 5, 6, 8, 1, 7, 9, 0], dtype=int64)

In [9]:
foo_1(array,11)

'No Item Found'

## Explanation : 
* <b> Step -1 </b> : i'm writing a function which accepts array and target number.
* <b> step-2 : </b> : if target not in arr: ,not in means it checks the target number in arr ,if target number is not in array then it prints the return statement of if .
* <b> step-3 : </b> :   differences = np.absolute(arr - target)  ,i'm substracting each number with the target number ,then i can easily find out the nearest indices of numbers .absolute ---> it rremoves the -ve simbol and gives absolute number 
* <b> step-4 : </b> :  i'm assigning argsort to the indices ,argsort --> it sorts the indices of numbers .
* <b> step-5 : </b> : then return the indices 

### 2. Write a user defined function foo_2 that takes a  2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.


In [75]:
def foo_2(arr, axis):
    if arr.ndim == 2:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts
    elif arr.ndim == 3:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts

In [76]:
array = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])
foo_2(array,axis=1)

array([4, 1, 2])

In [77]:
foo_2(array,axis=0)

array([2, 2, 2, 1])

In [78]:
arr1 = np.array([[[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]],
                 [[2, 0, 1, 0], [0, 5, 0, 0], [1, 2, 3, 4]]])
foo_2(arr1,axis=0)

array([[2, 1, 2, 1],
       [0, 2, 0, 0],
       [2, 1, 2, 1]])

## Explanation :
* <b> Step-1 </b> : creat a function which accepts array and axis .
arr ----> which is array , axis ----> in arrays we have axis ,when axis=0 it collapsing the rows ,axis=1 is for columns
* <b> step-2 </b> : if arr.ndim==2: ---> if the given array is 2 dim array then it executes the beneath of if statement .
* <b> step-3 </b> : x=np.where(arr != 0, 1, 0) "Where" Function to create a new array x with the same shape as the input array. The elements of x are 1((which is True) the corresponding elements of arr are not equal to 0 ,if it is equal to zero then it is 0(which is False ).
* <b> step-4 </b> :  counts=np.sum(x,axis=axis)---> sum of x ,is nothing but count of non zero elements.
* <b> step-5 </b> : returns counts 
* <b> step-6 </b> : the above functionality is same for 3 dim array 

###  3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [14]:
second_array=np.array([[85,88,89],  
                      [78,89,94], (which is True) 
                      [91,87,90],
                      [87,95,84]])

In [15]:
second_array

array([[85, 88, 89],
       [78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

In [16]:
def foo_2(array):
    x=np.any(second_array > 90, axis=1)
    result=array[x]                                   
    print(" students who scored greater than 90:")
    print(result)

In [17]:
foo_2(second_array)

 students who scored greater than 90:
[[78 89 94]
 [91 87 90]
 [87 95 84]]


## Eplanation :

* <b>step-1</b> :creating a numpy array ,with np.array function
* <b>step-2 </b> : here i'm creating function named foo_2,in that function i'm using (np.any) for accessing the students who got more than 90 .
* <b> step-3 </b> : np.any("condition"),it checks the condition we write in the paranthesis ,it prints the output as boolean type .
* <b> step-4</b> : in the conditon ,i'm mentioning axis=1 because ,it is a 2 dim array,in 2 dim array axis 1 is nothing but collpsing rows it checks the condition in row wise.
* <b> step-5</b> : again im writing boolean mask for the result ,then it prints the rows where the condition is true .

###  3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.


In [18]:
third_array=np.array([[120,150,130,110],
                    [200,180,220,250],
                    [90,100,95,110],     
                    [300,280,320,340]])

In [19]:
third_array

array([[120, 150, 130, 110],
       [200, 180, 220, 250],
       [ 90, 100,  95, 110],
       [300, 280, 320, 340]])

In [20]:
product1=third_array[0,:]
product2=third_array[1,:]
product3=third_array[2,:]
product4=third_array[3,:]

In [21]:
print(f'The mean of product1 is : {np.mean(product1)}') 
print(f'the mean of product2 is : {np.mean(product2)}')
print(f'the mean of product3 is : {np.mean(product3)}')  ## sales of product4 is highest 
print(f'the mean of product4 is : {np.mean(product4)}')

The mean of product1 is : 127.5
the mean of product2 is : 212.5
the mean of product3 is : 98.75
the mean of product4 is : 310.0


In [22]:
print(f'The median of product1 is : {np.median(product1)}')
print(f'the median of product2 is : {np.median(product2)}')
print(f'the median of product3 is : {np.median(product3)}')
print(f'the median of product4 is : {np.median(product4)}')

The median of product1 is : 125.0
the median of product2 is : 210.0
the median of product3 is : 97.5
the median of product4 is : 310.0


In [23]:
print(f'The standard_deviation of product1 is : {np.std(product1)}')
print(f'the standard_deviation of product2 is : {np.std(product2)}')
print(f'the standard_deviation of product3 is : {np.std(product3)}')
print(f'the standard_deviation of product4 is : {np.std(product4)}')

The standard_deviation of product1 is : 14.79019945774904
the standard_deviation of product2 is : 25.8602010819715
the standard_deviation of product3 is : 7.39509972887452
the standard_deviation of product4 is : 22.360679774997898


In [24]:
fst_mnth=third_array[:,0]
scnd_mnth=third_array[:,1]
thrd_mnth=third_array[:,2]
frth_mnth=third_array[:,3]

In [25]:
print(f'first month of sales : {np.sum(fst_mnth)}')
print(f'second month of sales : {np.sum(scnd_mnth)}')
print(f'third month of sales  : {np.sum(thrd_mnth)}')
print(f'fourth month of sales : {np.sum(frth_mnth)}')

first month of sales : 710
second month of sales : 710
third month of sales  : 765
fourth month of sales : 810


## Explanation : 
* <b> Step-1 </b> : finding mean for the all products by using np.mean() function ,it gives the mean .
* <b> step-2 </b> : finding median for all the products by using np.median() function .
* <b> step-3 </b> : finding median for all the products by using np.std() function .
*  <B> step-4 </B> : 4th month has highest sales 

###  Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.



In [60]:
x=np.random.randint(1,101,1000) ## printing numbers randomly by using random function in numpy

In [27]:
x

array([ 47,   6,  75,  86,   6,  31,  47,  95,  45,  43,  88,  78,  74,
        62,  86,  96,  64,  56,  34,  68,  44,  81, 100,  75,  76,  34,
        72,  52,  39,   3,  64,  16,  17,  64,  42,  12,  59,  67,  93,
        30,  82,  20,  23,  49,  17, 100,  71,  33,  32,  19,  73,  39,
        14,  47,  35,   2,  47,  69,  18,  98,  27,  90,  26,  70,  60,
        49,   1,  80,   5,  95,  89,  55,  49,  41,   1,  90,  33,  63,
         4,  20,  12,  63,   4,  69,  10,  43,  67,  89,   1,  38,  19,
        16,  93,  14,  55,  63,  34,  62,  71,  58,  27,  18,   4,  61,
        13,   6,  38,   1,  45,  67,  54,  58,  42,  29,  48,  79,  34,
        54,  53,  42,   3,  36,  38,  74,  76,  55,  30,   1,  79,  35,
        50,  14,  73,  19,  84,  40,   9,  75,  86,  32,  33,  79,  15,
        49,  38,  56,   6,  86,  36,  59,  85,  43,  38,  98,  35,  99,
        76,  74,  11,   1,  73,  52,  26,  95,  32, 100,  88,  21,  12,
        12,  22,  61,  99,  16,  71,  46,  66,  53,  99,  59,  9

In [83]:
def array(x):
    unique,No_unique = np.unique(x, return_counts=True)
    sorted = np.argsort(-No_unique)    ## it sorting in descending Order(max num to min num) ,Then we get the the highest counts 
    top_10_values = unique[sorted[:10]]   
    top_10_counts = No_unique[sorted[:10]]
    print(unique,No_unique,sep='\n\n\n')
    print('\n'"Top 10 most frequently occurring values:")
    for value, count in zip(top_10_values, top_10_counts):
        print( '\n'f" Number  : {value},       No_times_repeated  : {count}",sep='\n')

In [84]:
array(x)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


[12  5 10  6  7  7 11 10 11 13  9 14 10 10  9  9 11 10  8  8 17 11 14  9
  7 18 12  8 17 10 12  9 16  3  9 10 11 13 12 11  8 14 11 11 12  5 10 11
  8 12  1  9 11 10 11  6 10 12  8  9  4  8  7  6  5 15  8 10 15 15 11 10
 12 10  8  8  9  7 13  9  7 13 11  8 13  5  7  8 12 11 13 10 10  9 13  9
 19  6  9  9]

Top 10 most frequently occurring values:

 Number  : 97,       No_times_repeated  : 19

 Number  : 26,       No_times_repeated  : 18

 Number  : 29,       No_times_repeated  : 17

 Number  : 21,       No_times_repeated  : 17

 Number  : 33,       No_times_repeated  : 16

 Number  : 6

## Explanation : 

* <b> step-1 </b> : writing a function which accepts array.
* <b> step-2 </b> :  unique,No_unique = np.unique(x, return_counts=True)
* ---> unique = it prints the unique numbers(without repeated ).
* -----> no_unique : it gives the count of repeated unique numbers .
* <b> step-3 </b> :  sorted = np.argsort(-No_unique)  
* -----> argsort = it sorting the values 
* ---->(-No-unique) = it asscending in reverse order (max to min )
* <b> step-4 </b> : top_10_counts = No_unique[sorted[:10]] ---> accesing first 10 numbers which are more repeated 